notemp: true
printshellcmds: true
keep-going: true
resources: ['network_connections=3', 'mem_mb=750000']
use-conda: true
conda-frontend: 'mamba'
conda-prefix: '/pollard/home/bsmith/.snakemake/conda'
use-singularity: true
singularity-args: "--bind /pollard/ --bind /usr/local/cuda-10.1 --nv --bind /salilab/diva1/home/anaconda/anaconda3 --bind /scratch/bsmith"
singularity-prefix: '/pollard/home/bsmith/.snakemake/singularity'
config: ['USE_CUDA=1', 'MAX_THREADS=24', 'jupyter_port=8818']
